#!/bin/bash

echo "it is just uhh... different strokes"

#packages
apt install net-tools nnn curl pcmanfm-qt transmission-qt mpv simplescreenrecorder git libnotify-bin vim fastfetch figlet cowsay cmatrix suckless-tools i3 tor torsocks doas tmux macchanger flatpak tlp xorg
figlet "pretty darn amazing waow"

#privilege
echo "permit nopass debian as root" >> /etc/doas.conf
chown root:root /etc/doas.conf
chmod 0400 /etc/doas.conf
echo "alias sudo='doas'" >> ~/.bashrc
source ~/.bashrc

#desktop
echo "exec i3" > ~/.xinitrc

#config
mv config/99-swapiness.conf /etc/sysctl.d/
cp -r config/* ~/.config/
wget -qO /etc/hosts https://github.com/StevenBlack/hosts/raw/refs/heads/master/alternates/fakenews-gambling-porn-social/hosts && sed -i -e 's/#.*0.0.0.0/0.0.0.0/g' /etc/hosts
echo -e "nameserver 9.9.9.9\nnameserver 149.112.112.112" | sudo tee /etc/resolv.conf > /dev/null
